name: Security check - Go Sec 

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - ${{ github.event.repository.default_branch }}

jobs:
    golang-security-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ynniss/golang-security-action@master
              continue-on-error: true